# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ibkr-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 100Mi
#   accessModes:
#   - ReadWriteOnce
#   hostPath:
#     path: "/mnt/ibkr/util-data"

# ---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibkrweb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ibkr/web-data"
